In [1]:
import pandas as pd
from glob import glob

In [4]:
single_file_acc = pd.read_csv(
    "../../data/raw/MetaMotion/A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv"
)

In [5]:
single_file_gyr = pd.read_csv(
    "../../data/raw/MetaMotion/A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv"
)

In [6]:
files = glob("../../data/raw/MetaMotion/*.csv")

In [7]:
len(files)

187

In [8]:
data_path = "../../data/raw/MetaMotion\\"

In [9]:
f = files[2]

In [10]:
f

'../../data/raw/MetaMotion\\A-bench-heavy2_MetaWear_2019-01-14T14.27.00.784_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv'

In [11]:
participant = f.split("-")[0].replace(data_path, " ")
label = f.split("-")[1]
category = f.split("-")[2].rstrip("2")

In [13]:
participant

' A'

In [14]:
f.split("-")

['../../data/raw/MetaMotion\\A',
 'bench',
 'heavy2_MetaWear_2019',
 '01',
 '14T14.27.00.784_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv']

In [15]:
f.split("-")[0]

'../../data/raw/MetaMotion\\A'

In [16]:
df = pd.read_csv(f)

In [17]:
df

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g)
0,1547472421400,2019-01-14T14:27:01.400,0.00,-0.181,0.796,-0.383
1,1547472421480,2019-01-14T14:27:01.480,0.08,-0.192,0.823,-0.424
2,1547472421560,2019-01-14T14:27:01.560,0.16,-0.203,0.808,-0.421
3,1547472421640,2019-01-14T14:27:01.640,0.24,-0.217,0.833,-0.439
4,1547472421720,2019-01-14T14:27:01.720,0.32,-0.206,0.845,-0.446
...,...,...,...,...,...,...
151,1547472433480,2019-01-14T14:27:13.480,12.08,-0.094,0.924,-0.357
152,1547472433560,2019-01-14T14:27:13.560,12.16,-0.104,0.901,-0.369
153,1547472433640,2019-01-14T14:27:13.640,12.24,-0.087,0.881,-0.374
154,1547472433720,2019-01-14T14:27:13.720,12.32,-0.094,0.893,-0.373
155,1547472433800,2019-01-14T14:27:13.800,12.40,-0.100,0.907,-0.375

In [18]:
df["participant"] = participant
df["label"] = label
df["category"] = category
df

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category
0,1547472421400,2019-01-14T14:27:01.400,0.00,-0.181,0.796,-0.383,A,bench,heavy2_MetaWear_2019
1,1547472421480,2019-01-14T14:27:01.480,0.08,-0.192,0.823,-0.424,A,bench,heavy2_MetaWear_2019
2,1547472421560,2019-01-14T14:27:01.560,0.16,-0.203,0.808,-0.421,A,bench,heavy2_MetaWear_2019
3,1547472421640,2019-01-14T14:27:01.640,0.24,-0.217,0.833,-0.439,A,bench,heavy2_MetaWear_2019
4,1547472421720,2019-01-14T14:27:01.720,0.32,-0.206,0.845,-0.446,A,bench,heavy2_MetaWear_2019
...,...,...,...,...,...,...,...,...,...
151,1547472433480,2019-01-14T14:27:13.480,12.08,-0.094,0.924,-0.357,A,bench,heavy2_MetaWear_2019
152,1547472433560,2019-01-14T14:27:13.560,12.16,-0.104,0.901,-0.369,A,bench,heavy2_MetaWear_2019
153,1547472433640,2019-01-14T14:27:13.640,12.24,-0.087,0.881,-0.374,A,bench,heavy2_MetaWear_2019
154,1547472433720,2019-01-14T14:27:13.720,12.32,-0.094,0.893,-0.373,A,bench,heavy2_MetaWear_2019
155,1547472433800,2019-01-14T14:27:13.800,12.40,-0.100,0.907,-0.375,A,bench,heavy2_MetaWear_2019

In [19]:
acc_df = pd.DataFrame()
gyr_df = pd.DataFrame()

acc_set = 1
gyr_set = 1

In [20]:
for f in files:
    participant = f.split("-")[0].replace(data_path, " ")
    label = f.split("-")[1]
    category = f.split("-")[2].rstrip("23").rstrip("_MetaWear_2019")

    df = pd.read_csv(f)

    df["participant"] = participant
    df["label"] = label
    df["category"] = category

    if "Accelerometer" in f:
        df["set"] = acc_set
        acc_set += 1
        acc_df = pd.concat([acc_df, df])
    if "Gyroscope" in f:
        df["set"] = gyr_set
        gyr_set += 1
        gyr_df = pd.concat([gyr_df, df])

In [21]:
acc_df

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
0,1547219408431,2019-01-11T16:10:08.431,0.00,0.010,0.964,-0.087,A,bench,heavy,1
1,1547219408511,2019-01-11T16:10:08.511,0.08,0.000,0.961,-0.069,A,bench,heavy,1
2,1547219408591,2019-01-11T16:10:08.591,0.16,0.001,0.974,-0.087,A,bench,heavy,1
3,1547219408671,2019-01-11T16:10:08.671,0.24,-0.012,0.971,-0.084,A,bench,heavy,1
4,1547219408751,2019-01-11T16:10:08.751,0.32,-0.013,0.954,-0.094,A,bench,heavy,1
...,...,...,...,...,...,...,...,...,...,...
237,1547666063089,2019-01-16 20:14:23.089,18.96,0.012,0.596,0.815,E,squat,heavy,94
238,1547666063169,2019-01-16 20:14:23.169,19.04,0.009,0.528,0.821,E,squat,heavy,94
239,1547666063249,2019-01-16 20:14:23.249,19.12,0.015,0.554,0.746,E,squat,heavy,94
240,1547666063329,2019-01-16 20:14:23.329,19.20,0.006,0.574,0.824,E,squat,heavy,94
241,1547666063409,2019-01-16 20:14:23.409,19.28,0.015,0.588,0.826,E,squat,heavy,94

In [22]:
gyr_df

,epoch (ms),time (01:00),elapsed (s),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
0,1547219408351,2019-01-11T16:10:08.351,0.00,0.122,-5.488,-3.841,A,bench,heavy,1
1,1547219408391,2019-01-11T16:10:08.391,0.04,2.195,-9.695,-0.610,A,bench,heavy,1
2,1547219408431,2019-01-11T16:10:08.431,0.08,2.622,-8.110,-4.024,A,bench,heavy,1
3,1547219408471,2019-01-11T16:10:08.471,0.12,1.951,-4.695,-4.634,A,bench,heavy,1
4,1547219408511,2019-01-11T16:10:08.511,0.16,1.524,-2.561,-2.500,A,bench,heavy,1
...,...,...,...,...,...,...,...,...,...,...
487,1547666063314,2019-01-16 20:14:23.314,19.48,-1.707,-0.671,1.585,E,squat,heavy,93
488,1547666063354,2019-01-16 20:14:23.354,19.52,0.915,0.305,2.988,E,squat,heavy,93
489,1547666063394,2019-01-16 20:14:23.394,19.56,5.854,-2.561,1.463,E,squat,heavy,93
490,1547666063434,2019-01-16 20:14:23.434,19.60,4.268,0.549,-0.305,E,squat,heavy,93
491,1547666063474,2019-01-16 20:14:23.474,19.64,-1.098,1.768,-0.122,E,squat,heavy,93

In [23]:
acc_df.info()
pd.to_datetime(df["epoch (ms)"], unit="ms")
pd.to_datetime(df["time (01:00)"])

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23578 entries, 0 to 241
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   epoch (ms)    23578 non-null  int64
 1   time (01:00)  23578 non-null  object
 2   elapsed (s)   23578 non-null  float64
 3   x-axis (g)    23578 non-null  float64
 4   y-axis (g)    23578 non-null  float64
 5   z-axis (g)    23578 non-null  float64
 6   participant   23578 non-null  object
 7   label         23578 non-null  object
 8   category      23578 non-null  object
 9   set           23578 non-null  int64
dtypes: float64(4), int64(2), object(4)
memory usage: 2.0+ MB

0     2019-01-16 20:14:03.834
1     2019-01-16 20:14:03.874
2     2019-01-16 20:14:03.914
3     2019-01-16 20:14:03.954
4     2019-01-16 20:14:03.994
                ...
487   2019-01-16 20:14:23.314
488   2019-01-16 20:14:23.354
489   2019-01-16 20:14:23.394
490   2019-01-16 20:14:23.434
491   2019-01-16 20:14:23.474
Name: time (01:00), Length: 492, dtype: datetime64[ns]

In [24]:
acc_df.index = pd.to_datetime(acc_df["epoch (ms)"], unit="ms")

In [25]:
gyr_df.index = pd.to_datetime(gyr_df["epoch (ms)"], unit="ms")

In [26]:
acc_df.drop(columns=["epoch (ms)", "time (01:00)", "elapsed (s)"], inplace=True)

In [27]:
gyr_df.drop(columns=["epoch (ms)", "time (01:00)", "elapsed (s)"], inplace=True)

In [28]:
files = glob("../../data/raw/MetaMotion/*.csv")


def read_data_from_files(files):
    acc_df = pd.DataFrame()
    gyr_df = pd.DataFrame()

    acc_set = 1
    gyr_set = 1

    for f in files:
        participant = f.split("-")[0].replace(data_path, " ")
        label = f.split("-")[1]
        category = f.split("-")[2].rstrip("23").rstrip("_MetaWear_2019")

        df = pd.read_csv(f)

        df["participant"] = participant
        df["label"] = label
        df["category"] = category

        if "Accelerometer" in f:
            df["set"] = acc_set
            acc_set += 1
            acc_df = pd.concat([acc_df, df])
        if "Gyroscope" in f:
            df["set"] = gyr_set
            gyr_set += 1
            gyr_df = pd.concat([gyr_df, df])

    acc_df.index = pd.to_datetime(acc_df["epoch (ms)"], unit="ms")
    gyr_df.index = pd.to_datetime(gyr_df["epoch (ms)"], unit="ms")

    acc_df.drop(columns=["epoch (ms)", "time (01:00)", "elapsed (s)"], inplace=True)
    gyr_df.drop(columns=["epoch (ms)", "time (01:00)", "elapsed (s)"], inplace=True)

    return acc_df, gyr_df


acc_df, gyr_df = read_data_from_files(files)

In [29]:
acc_df

,x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
epoch (ms),,,,,,,
2019-01-11 15:10:08.431,0.010,0.964,-0.087,A,bench,heavy,1
2019-01-11 15:10:08.511,0.000,0.961,-0.069,A,bench,heavy,1
2019-01-11 15:10:08.591,0.001,0.974,-0.087,A,bench,heavy,1
2019-01-11 15:10:08.671,-0.012,0.971,-0.084,A,bench,heavy,1
2019-01-11 15:10:08.751,-0.013,0.954,-0.094,A,bench,heavy,1
...,...,...,...,...,...,...,...
2019-01-16 19:14:23.089,0.012,0.596,0.815,E,squat,heavy,94
2019-01-16 19:14:23.169,0.009,0.528,0.821,E,squat,heavy,94
2019-01-16 19:14:23.249,0.015,0.554,0.746,E,squat,heavy,94
2019-01-16 19:14:23.329,0.006,0.574,0.824,E,squat,heavy,94
2019-01-16 19:14:23.409,0.015,0.588,0.826,E,squat,heavy,94

In [30]:
gyr_df

,x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,
2019-01-11 15:10:08.351,0.122,-5.488,-3.841,A,bench,heavy,1
2019-01-11 15:10:08.391,2.195,-9.695,-0.610,A,bench,heavy,1
2019-01-11 15:10:08.431,2.622,-8.110,-4.024,A,bench,heavy,1
2019-01-11 15:10:08.471,1.951,-4.695,-4.634,A,bench,heavy,1
2019-01-11 15:10:08.511,1.524,-2.561,-2.500,A,bench,heavy,1
...,...,...,...,...,...,...,...
2019-01-16 19:14:23.314,-1.707,-0.671,1.585,E,squat,heavy,93
2019-01-16 19:14:23.354,0.915,0.305,2.988,E,squat,heavy,93
2019-01-16 19:14:23.394,5.854,-2.561,1.463,E,squat,heavy,93
2019-01-16 19:14:23.434,4.268,0.549,-0.305,E,squat,heavy,93
2019-01-16 19:14:23.474,-1.098,1.768,-0.122,E,squat,heavy,93

In [31]:
df_merged = pd.concat([acc_df.iloc[:, :3], gyr_df], axis=1)

In [32]:
acc_df.iloc[:, :3]

                         x-axis (g)  y-axis (g)  z-axis (g)
epoch (ms)
2019-01-11 15:10:08.431       0.010       0.964      -0.087
2019-01-11 15:10:08.511       0.000       0.961      -0.069
2019-01-11 15:10:08.591       0.001       0.974      -0.087
2019-01-11 15:10:08.671      -0.012       0.971      -0.084
2019-01-11 15:10:08.751      -0.013       0.954      -0.094
...                             ...         ...         ...
2019-01-16 19:14:23.089       0.012       0.596       0.815
2019-01-16 19:14:23.169       0.009       0.528       0.821
2019-01-16 19:14:23.249       0.015       0.554       0.746
2019-01-16 19:14:23.329       0.006       0.574       0.824
2019-01-16 19:14:23.409       0.015       0.588       0.826

[23578 rows x 3 columns]

In [33]:
df_merged

,x-axis (g),y-axis (g),z-axis (g),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.950,NaN,NaN,NaN,-10.671,-1.524,5.976,B,bench,heavy,30.0
2019-01-11 15:08:04.990,NaN,NaN,NaN,-8.720,-2.073,3.171,B,bench,heavy,30.0
2019-01-11 15:08:05.030,NaN,NaN,NaN,0.488,-3.537,-4.146,B,bench,heavy,30.0
2019-01-11 15:08:05.070,NaN,NaN,NaN,0.244,-5.854,3.537,B,bench,heavy,30.0
2019-01-11 15:08:05.110,NaN,NaN,NaN,-0.915,0.061,-2.805,B,bench,heavy,30.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:35:13.382,-0.060,-1.021,-0.058,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.462,-0.035,-1.037,-0.026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.542,-0.045,-1.029,-0.033,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.622,-0.039,-1.027,-0.039,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.702,-0.049,-1.031,-0.049,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
days = [g for n, g in df_merged.groupby(pd.Grouper(freq="D"))]

In [35]:
days[-1]

,x-axis (g),y-axis (g),z-axis (g),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-20 17:22:25.756,NaN,NaN,NaN,1.341,1.463,0.671,E,rest,sitting,80.0
2019-01-20 17:22:25.796,NaN,NaN,NaN,1.098,1.098,0.976,E,rest,sitting,80.0
2019-01-20 17:22:25.836,NaN,NaN,NaN,0.183,-2.195,0.305,E,rest,sitting,80.0
2019-01-20 17:22:25.876,NaN,NaN,NaN,0.061,-2.195,0.183,E,rest,sitting,80.0
2019-01-20 17:22:25.916,NaN,NaN,NaN,0.305,0.915,1.159,E,rest,sitting,80.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:35:13.382,-0.060,-1.021,-0.058,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.462,-0.035,-1.037,-0.026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.542,-0.045,-1.029,-0.033,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.622,-0.039,-1.027,-0.039,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.702,-0.049,-1.031,-0.049,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
len(days)  # we have 10 different dfs as o/p of days. We have to concatenate it while resampling

10

In [37]:
df_merged.groupby(pd.Grouper(freq="D"))

In [38]:
df_merged

,x-axis (g),y-axis (g),z-axis (g),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.950,NaN,NaN,NaN,-10.671,-1.524,5.976,B,bench,heavy,30.0
2019-01-11 15:08:04.990,NaN,NaN,NaN,-8.720,-2.073,3.171,B,bench,heavy,30.0
2019-01-11 15:08:05.030,NaN,NaN,NaN,0.488,-3.537,-4.146,B,bench,heavy,30.0
2019-01-11 15:08:05.070,NaN,NaN,NaN,0.244,-5.854,3.537,B,bench,heavy,30.0
2019-01-11 15:08:05.110,NaN,NaN,NaN,-0.915,0.061,-2.805,B,bench,heavy,30.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:35:13.382,-0.060,-1.021,-0.058,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.462,-0.035,-1.037,-0.026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.542,-0.045,-1.029,-0.033,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.622,-0.039,-1.027,-0.039,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.702,-0.049,-1.031,-0.049,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
days = [g for n, g in df_merged.groupby(pd.Grouper(freq="D"))]

In [47]:
df_merged = pd.concat([acc_df.iloc[:, :3], gyr_df], axis=1)

In [48]:
df_merged.columns = [
    "acc_x",
    "acc_y",
    "acc_z",
    "gyr_x",
    "gyr_y",
    "gyr_z",
    "participant",
    "label",
    "category",
    "set",
]

In [49]:
df_merged

,acc_x,acc_y,acc_z,gyr_x,gyr_y,gyr_z,participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.950,NaN,NaN,NaN,-10.671,-1.524,5.976,B,bench,heavy,30.0
2019-01-11 15:08:04.990,NaN,NaN,NaN,-8.720,-2.073,3.171,B,bench,heavy,30.0
2019-01-11 15:08:05.030,NaN,NaN,NaN,0.488,-3.537,-4.146,B,bench,heavy,30.0
2019-01-11 15:08:05.070,NaN,NaN,NaN,0.244,-5.854,3.537,B,bench,heavy,30.0
2019-01-11 15:08:05.110,NaN,NaN,NaN,-0.915,0.061,-2.805,B,bench,heavy,30.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:35:13.382,-0.060,-1.021,-0.058,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.462,-0.035,-1.037,-0.026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.542,-0.045,-1.029,-0.033,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.622,-0.039,-1.027,-0.039,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.702,-0.049,-1.031,-0.049,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
sampling = {
    "acc_x": "mean",
    "acc_y": "mean",
    "acc_z": "mean",
    "gyr_x": "mean",
    "gyr_y": "mean",
    "gyr_z": "mean",
    "participant": "last",
    "label": "last",
    "category": "last",
    "set": "last",
}

In [51]:
days = [g for n, g in df_merged.groupby(pd.Grouper(freq="D"))]

In [52]:
data_resampled = pd.concat(
    [df.resample(rule="200ms").apply(sampling).dropna() for df in days]
)

In [53]:
data_resampled["set"] = data_resampled["set"].astype("int")

In [54]:
data_resampled.to_pickle("../../data/interim/01_data_processed.pkl")

In [55]:
data_resampled

,acc_x,acc_y,acc_z,gyr_x,gyr_y,gyr_z,participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:05.200,0.013500,0.977000,-0.071000,-1.8904,2.4392,0.9388,B,bench,heavy,30
2019-01-11 15:08:05.400,-0.001500,0.970500,-0.079500,-1.6826,-0.8904,2.1708,B,bench,heavy,30
2019-01-11 15:08:05.600,0.001333,0.971667,-0.064333,2.5608,-0.2560,-1.4146,B,bench,heavy,30
2019-01-11 15:08:05.800,-0.024000,0.957000,-0.073500,8.0610,-4.5244,-2.0730,B,bench,heavy,30
2019-01-11 15:08:06.000,-0.028000,0.957667,-0.115000,2.4390,-1.5486,-3.6098,B,bench,heavy,30
...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:33:27.000,-0.048000,-1.041500,-0.076500,1.4146,-5.6218,0.2926,E,row,medium,90
2019-01-20 17:33:27.200,-0.037000,-1.030333,-0.053333,-2.7684,-0.5854,2.2440,E,row,medium,90
2019-01-20 17:33:27.400,-0.060000,-1.031000,-0.082000,2.8416,-5.1342,-0.1220,E,row,medium,90
2019-01-20 17:33:27.600,-0.038667,-1.025667,-0.044667,-0.2318,0.2562,1.1220,E,row,medium,90
2019-01-20 17:33:27.800,-0.044000,-1.034000,-0.059000,1.0980,-4.0240,0.9760,E,row,medium,90